### ISSUE TITLE
Bad argument error when trying to Turn on/off Big body cheat

### ISSUE THREAD

**Issue by MDP43140** [ABJ4403/Payback2_CHEATus#1] opened 2022-01-07 15:21 UTC
So i want to search Payback 2 cheats (not usual gold,ammo,or other nonsense), and i found your script.
i play payback 2 offline with cheats and testing every cheat. but some had errors

How To Reproduce:
- Open PB2 and GG
- Run the script
- Turn on/off Big body cheat, Select "Big Body", And select either "ON" or "OFF"

Errors:
bad argument #1 to gg.addListItems (nil: table expected, got nil) (field 'addListItems')

**Comment by ABJ4403** [comment] 2022-01-07 15:30
hmm... this might be caused by line 124:
gg.setRanges(gg.REGION_C_BSS | gg.REGION_C_ALLOC | gg.REGION_ANONYMOUS)
actually i dont know how these works though XD

**Comment by ABJ4403** [comment] 2022-01-08 03:33
It should be fixed now :)

**Closed by ABJ4403** 2022-01-08 03:33 UTC
Labels: bug, good first issue
